# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
#
# http://docs.travis-ci.com/user/customizing-the-build/
# http://lint.travis-ci.org/

os: linux
dist: trusty
sudo: required
services: docker
language: c

env:
  global:
    #- http_proxy="http://example.com"
    - INTENT="deb" # build and upload deb packages
  matrix:
    # Distribution Name and Version
    - DIST="debian:jessie"
    - DIST="debian:testing"
    - DIST="ubuntu:trusty"
    - DIST="ubuntu:wily"
    - DIST="ubuntu:xenial"
    - INTENT="distcheck" DIST="ubuntu:wily" # run and succeed in 'distcheck'
matrix:
  allow_failures:
    - env: DIST="ubuntu:xenial"
  fast_finish: true

before_install:
  # Build variable setup
  - export DISTNAME="${DIST%:*}" DISTRELEASE="${DIST#*:}" # Example: DIST=debian:jessie DISTNAME=debian DISTRELEASE=jessie
  - export BINTRAYREPO="deb [trusted=yes] https://dl.bintray.com/beast-team/deb $DISTRELEASE main"
  - echo "DIST=$DIST DISTNAME=$DISTNAME DISTRELEASE=$DISTRELEASE BINTRAYREPO='$BINTRAYREPO'"
  # Sample environment
  - uname -a
  - cat /etc/os-release
  - pwd
  - free -tm
  - make --version
  - python --version
  - $CC --version

install:
  # Complete history is required for monotonic revisioning
  - travis_retry git fetch --unshallow
  # Configure Dockerfile by substituting @VAR@ with $VAR
  - ./buildtool.sh applyenv .travis.docker > Dockerfile
  # Build and run tests, create packages
  - docker build -t rapicorn .

script:
  # Upload packages
  - [ $INTENT != deb ] || docker run -ti --rm rapicorn /bin/bash -c \
        "export BINTRAY_APITOKEN=$BINTRAY_APITOKEN && ls -al && rapicorn/buildtool.sh bintrayup beast-team deb/rapicorn $DISTRELEASE *.deb"
  # Test package installation from remote location
  - [ $INTENT != deb ] || sleep 60 && travis_retry docker run -ti --rm rapicorn /bin/bash -c \
        "set -x && retry apt-get -y install apt-transport-https ca-certificates &&
        echo '$BINTRAYREPO' | tee /etc/apt/sources.list.d/bintray-beast-team.list &&
        retry apt-get update && retry apt-get -y install rapicorn"
  - docker ps -a

after_success:
  - echo "Done, all OK!"

notifications:
  irc:
    channels:
      - "irc.gimp.org#beast"
    on_success: change # always / never / change
    on_failure: change # always / never / change
    skip_join: true
  email: false
    #recipients:
    #  - rapicorn@googlegroups.com
    #on_success: change
    #on_failure: change
