# This Source Code Form is licensed MPLv2: http://mozilla.org/MPL/2.0
#
# http://docs.travis-ci.com/user/customizing-the-build/
# http://lint.travis-ci.org/

language: cpp

os:
  - linux

dist: trusty

compiler:
  - gcc
  #- clang

matrix:
  fast_finish: true

#sudo: false   # http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required # needed to install cython and libcroco3-dev

addons:
  apt:
    sources: # https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
      - ubuntu-toolchain-r-test
    packages: [
      # g++ >= 4.8 is required for -std=c++11
      gcc-5, g++-5,
      # Rapicorn-14.10 dependencies
      libcairo2-dev, libpango1.0-dev, python2.7-dev, libxml2-dev, libgdk-pixbuf2.0-dev, libreadline6-dev,
      # Rapicorn-15.09 dependencies
      cython, libcroco3-dev,
      # devel-mode dependencies
      intltool, autoconf-archive, bison, flex, pandoc, doxygen, graphviz, texlive-binaries, xvfb,
      pbuilder, debootstrap, devscripts, debhelper, lintian ]

before_install:
  - uname -a
  - cat /etc/os-release
  - pwd
  - free -tm
  - make --version
  - autoconf --version
  - automake --version
  - python --version
  - flex --version
  - bison --version
  - which doxygen && doxygen --version
  - which bibtex && bibtex --version
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - $CXX --version

install:
  # a complete repository is required for versioned package builds
  - travis_retry git fetch --unshallow
  - git clean -f && pwd
  # show CI config
  - ./citool.sh config
  # sources for build packages
  - SOURCES=$'deb [trusted=yes] https://dl.bintray.com/beast-team/deb vivid main'
  # setup pbuilder environment
  - travis_retry sudo ./citool.sh pcreate vivid "$SOURCES"
  #- echo 'apt-get -y install ccache' | sudo pbuilder --login --save-after-login
  # packages needed for an upstream git build
  - P="build-essential automake autoconf autoconf-archive libtool intltool bison flex"
    P="$P libcairo2-dev libcroco3-dev libpango1.0-dev python2.7-dev libxml2-dev libgdk-pixbuf2.0-dev libreadline6-dev"
    P="$P cython doxygen graphviz texlive-binaries xvfb pandoc git"
  # build dist tarball
  - sudo ./citool.sh pdist $P
  # check/show single dist tarball
  - TARBALL=`ls cidir/*tar.xz | head -1` && ls -dl $TARBALL | tee /dev/stderr | test 1 -eq `wc -l`
  # build debian packages
  - EMAIL=rapicorn@googlegroups.com sudo ./citool.sh pbuild $TARBALL debian/
  - ls -al "cidir/"

before_script:
  - true

script:
  # upload debian packages
  - ./citool.sh bintrayup beast-team vivid deb/rapicorn cidir/*.deb

after_success:
  - echo "Done, all OK!"

notifications:
  irc:
    channels:
      - "irc.gimp.org#beast"
    on_failure: change
  email: false
    #recipients:
    #  - rapicorn@googlegroups.com
    #on_success: change
    #on_failure: change
