# This Source Code Form is licensed MPLv2: http://mozilla.org/MPL/2.0
#
# http://docs.travis-ci.com/user/customizing-the-build/
# http://lint.travis-ci.org/

language: cpp

os:
  - linux

dist: trusty

compiler:
  - gcc
  #- clang

matrix:
  fast_finish: true

#sudo: false   # http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required # needed to install cython and libcroco3-dev

addons:
  apt:
    sources: # https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
      - ubuntu-toolchain-r-test
    packages: [
      # g++ >= 4.8 is required for -std=c++11
      gcc-5, g++-5,
      # Rapicorn-14.10 dependencies
      libcairo2-dev, libpango1.0-dev, python2.7-dev, libxml2-dev, libgdk-pixbuf2.0-dev, libreadline6-dev,
      # Rapicorn-15.09 dependencies
      cython, libcroco3-dev,
      # devel-mode dependencies
      intltool, autoconf-archive, bison, flex, pandoc, doxygen, graphviz, texlive-binaries, xvfb,
      pbuilder, debootstrap, devscripts, debhelper ]

before_install:
  - uname -a
  - cat /etc/lsb-release
  - pwd
  - free -tm
  - make --version
  - autoconf --version
  - automake --version
  - python --version
  - flex --version
  - bison --version
  - which doxygen && doxygen --version
  - which bibtex && bibtex --version
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - $CXX --version

install:
  - travis_retry sudo apt-get install -y libcroco3-dev cython
  - travis_retry git fetch --unshallow && git clean -f && ls -al
  - ./autogen.sh
  - make -j`nproc` V=1
  - make -j`nproc` check V=1
  - sudo make -j`nproc` install V=1
  - make -j`nproc` installcheck V=1
  - make dist V=1
  - sudo make -j`nproc` uninstall V=1
  - make -j`nproc` clean V=1
  - TARBALL=`ls rapicorn-[0-9]*[0-9].tar.xz` && ls -dl $TARBALL | tee /dev/stderr | test 1 -eq `wc -l` # force uniq
  - travis_retry sudo pbuilder create --distribution vivid --debootstrapopts --variant=buildd
  # - travis_retry sudo pbuilder update
  - VCSREVISION=`debian/git-revision.sh 0travis$TRAVIS_JOB_NUMBER` && echo "$VCSREVISION"
  - LOGMESSAGE="Automatic travis-ci snapshot, git commit "`git rev-parse HEAD` && echo "$LOGMESSAGE"
  - USE_PBUILDER=true EMAIL=rapicorn@googlegroups.com
    debian/mkdeb.sh debian/ $TARBALL "$VCSREVISION" "$LOGMESSAGE"
  - echo "Running lintian..." && lintian *dsc *deb || true
  - ls -al

before_script:
  - true

script:
  - F=`ls ./rapicorn-*_*-1_amd64.deb` && test `wc -w <<<$F` -eq 1 &&
    URL="https://api.bintray.com/content/beast-team/deb/rapicorn/snapshot/$F" &&
    OPTS="deb_distribution=vivid;deb_component=main;deb_architecture=amd64;override=0;publish=1" &&
    curl -f -T "$F" "-ubeast-team:$BINTRAY_APITOKEN" "$URL;$OPTS"

after_success:
  - echo "Done, build OK!"

notifications:
  irc:
    channels:
      - "irc.gimp.org#beast"
    on_failure: change
  email: false
    #recipients:
    #  - rapicorn@googlegroups.com
    #on_success: change
    #on_failure: change
