# This Source Code Form is licensed MPLv2: http://mozilla.org/MPL/2.0
#
# http://docs.travis-ci.com/user/customizing-the-build/
# http://lint.travis-ci.org/

language: cpp

os:
  - linux

dist: trusty

compiler:
  - gcc
  #- clang

matrix:
  fast_finish: true

#sudo: false   # http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required # needed to install cython and libcroco3-dev

addons:
  apt:
    sources: # https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
      - ubuntu-toolchain-r-test
    packages: [
      # g++ >= 4.8 is required for -std=c++11
      gcc-5, g++-5,
      # Rapicorn-14.10 dependencies
      libcairo2-dev, libpango1.0-dev, python2.7-dev, libxml2-dev, libgdk-pixbuf2.0-dev, libreadline6-dev,
      # Rapicorn-15.09 dependencies
      cython, libcroco3-dev,
      # devel-mode dependencies
      intltool, autoconf-archive, bison, flex, pandoc, doxygen, graphviz, texlive-binaries, xvfb ]

before_install:
  - uname -a
  - cat /etc/lsb-release
  - pwd
  - free -tm
  - make --version
  - autoconf --version
  - automake --version
  - python --version
  - flex --version
  - bison --version
  - which doxygen && doxygen --version
  - which bibtex && bibtex --version
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - $CXX --version

install:
  - travis_retry sudo apt-get install -y libcroco3-dev
  - travis_retry sudo pip install 'cython>=0.20.2'
  - git clean -f
  - ./autogen.sh

before_script:
  - make V=1

script:
  - make check V=1
  - sudo make install V=1
  - make installcheck V=1
  - make dist V=1
  - sudo make uninstall V=1
  - make clean

after_success:
  - echo "Done, build OK!"

notifications:
  irc:
    channels:
      - "irc.gimp.org#beast"
  email: false
    #recipients:
    #  - rapicorn@googlegroups.com
    #on_success: change
    #on_failure: change
