# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
#
# http://docs.travis-ci.com/user/customizing-the-build/
# http://lint.travis-ci.org/

os: linux
dist: trusty
sudo: required
services: docker
language: c
matrix:
  fast_finish: true

env:
  # global:
  #   - BINTRAYUP=""
  matrix:
    - DOCKERDIST="debian:jessie" BINTRAYUP="debian"
    - DOCKERDIST="ubuntu:wily",  BINTRAYUP="ubuntu"
    - DOCKERDIST="ubuntu:latest", BINTRAYUP=""

before_install:
  - uname -a
  - cat /etc/os-release
  - pwd
  - free -tm
  - make --version
  - python --version
  - $CC --version

install:
  - travis_retry git fetch --unshallow
  # Build and run tests, create packages
  - sed "s&@DOCKERDIST@&$DOCKERDIST&" < .travis.docker > Dockerfile
  - docker build -t rapicorn .

script:
  # Upload packages
  - test -z "$BINTRAYUP" || docker run -ti --rm rapicorn /bin/bash -c \
        "pwd && ls -al && rapicorn/buildtool.sh bintrayup beast-team $BINTRAYUP deb/rapicorn *.deb"
  - docker ps -a

after_success:
  - echo "Done, all OK!"

notifications:
  irc:
    channels:
      - "irc.gimp.org#beast"
    on_success: change # always / never / change
    on_failure: change # always / never / change
    skip_join: true
  email: false
    #recipients:
    #  - rapicorn@googlegroups.com
    #on_success: change
    #on_failure: change
